### ISSUE TITLE
accessing agent components

### ISSUE THREAD

**Issue by EdenMelaku** [EdenMelaku/Wumpus_World_Game#12]
i was just wondering how i can actually set a a sensor and actually receive a decision?

`agent::IntelligentAgent intelligentAgent= agent::IntelligentAgent::IntelligentAgent();`

after creating this object i should be able to set the sensor information and tell me how can i receive an actuator or the decision?

**Comment by arisema** [comment]
using the agent::IntelligentAgent::go(std::pair<int, int> room, DataStructures::Percepts roomPercpetion) function. The Percepts will be the sensory information passed to the agent and the function will return an DataStructures::Decision object.
