### ISSUE TITLE
changing the go() function in IA

### ISSUE THREAD

**Issue by EdenMelaku** [EdenMelaku/Wumpus_World_Game#13]
` Percepts p;
    p.breeze = true;
    p.bump = true;
    p.stench = true;

    std::pair<int, int> r = std::make_pair(1, 1);
    
    ia_sensor.add_percept(std::make_pair(1, 1), p);
    

    decision = ia_inferer.infer(r);`

all this line of code has to be changed in to 

`decision = ia_inferer.infer(p);`

because even the initial state will be added as a percept p 
and i don't see the point of setting all the percepts as true,,,,,,,,, i don't know isn't it supposed to come from the world 
i was thinking to have something like this 
` agent::IntelligentAgent intelligentAgent= agent::IntelligentAgent::IntelligentAgent();
    
    Sensor sensor=pg.get_initial_perception();
    Decision decision=intelligentAgent.go(pg.p);

    while (!pg.is_game_over())
    {   printUI();
        chrono::milliseconds timespan(1000); 
        this_thread::sleep_for(timespan);
        decision=intelligentAgent.decision;

        actions action=decision_to_action(decision);
        pg.action=action;
        pg.execute();
        
    }`

**Comment by arisema** [comment]
Updated to fit requirements.
